#!/usr/bin/env bash

# Copyright 2020 Ricardo Cordeiro <ricardo.cordeiro@tux.com.pt>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eufo pipefail

echo "INFO: Starting git's pre-push hook"
echo

GIT_ROOT_DIR="$(git rev-parse --show-toplevel)"
pushd "${GIT_ROOT_DIR}" > /dev/null

if [[ ! -f "local_env.sh" ]]; then
	echo "ERROR: Was expecting local_env.sh to exist. Please setup your local testing environment as explained on the README.md file."
	exit 1
elif [[ ! -x "scripts/local_test.bash" ]]; then
	echo "ERROR: Expected an executable scripts/local_test.bash."
	exit 1
fi

if ! source local_env.sh; then
	echo "ERROR: Failed to source local_env.sh"
	exit 1
fi

if ! scripts/local_test.bash; then
	echo "ERROR: Failed to execute scripts/local_test.bash"
	exit 1
fi

popd > /dev/null

echo "INFO: Finished git's pre-push hook successfully."
echo

exit 0
