# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# The provider version(s) on this file are automatically upgraded by dependabot
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.43.0"
    }
  }
}